user_config:

data:
  trainX: data/raw/P8_Cityscapes_leftImg8bit_trainvaltest/leftImg8bit/train
  trainY: data/raw/P8_Cityscapes_gtFine_trainvaltest/gtFine/train
  validX: data/raw/P8_Cityscapes_leftImg8bit_trainvaltest/leftImg8bit/val
  validY: data/raw/P8_Cityscapes_gtFine_trainvaltest/gtFine/val
  input_height: 128
  input_width: 256

generator:
  workers: 12
  batch_size: 16
  auglist:
  seed: 42
  
model:
  loss_function: DiceLoss
  optimizer: adam
  no_epochs: 15
  verbosity: 2
  name: UNET_VANILLA
  backbone: vanilla
  model_type: unetmini


mlflow:
  experiment_name: baseline_model
  run_name: unetmini
