user_config:

data:
  trainX: data/raw/P8_Cityscapes_leftImg8bit_trainvaltest/leftImg8bit/train
  trainY: data/raw/P8_Cityscapes_gtFine_trainvaltest/gtFine/train
  validX: data/raw/P8_Cityscapes_leftImg8bit_trainvaltest/leftImg8bit/val
  validY: data/raw/P8_Cityscapes_gtFine_trainvaltest/gtFine/val
  input_height: 144
  input_width: 288

generator:
  workers: 12
  batch_size: 16
  auglist:
    geo: caca_boudin
    col: 
    ker: 
  mosaic:
  oversampling:
  seed: 42
  
model:
  loss_function: DiceLoss
  optimizer: adam
  no_epochs: 15
  verbosity: 2
  name: UNET
  backbone: mobilenetv2, resnet101, efficientnetb4
  model_type: unet, fpn, pspnet


mlflow:
  experiment_name: models_without_aug
