user_config:

data:
  trainX: data/raw/P8_Cityscapes_leftImg8bit_trainvaltest/leftImg8bit/train
  trainY: data/raw/P8_Cityscapes_gtFine_trainvaltest/gtFine/train
  validX: data/raw/P8_Cityscapes_leftImg8bit_trainvaltest/leftImg8bit/val
  validY: data/raw/P8_Cityscapes_gtFine_trainvaltest/gtFine/val
  input_height: 128
  input_width: 256

generator:
  workers: 12
  batch_size: 16
  auglist: hflip_rgb_bright_mblur
  
model:
  loss_function: DiceLoss
  optimizer: adam
  no_epochs: 15
  verbosity: 2
  name: P_UNET
  backbone: resnet101
  model_type: unet


mlflow:
  experiment_name: pretrained_unet_resnet
  run_name: pretrained_unet_resnet_trial
