user_config:

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    direction: [maximize, maximize]
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_trials: 30
    n_jobs: 1
    sampler:
      seed: 42
    params:
      generator.auglist.geo: choice(hflip,rotateb,rdcrop)
      generator.auglist.ker: choice(gnoise,mblur)
      generator.auglist.clim: interval(0, 0.4)
      generator.auglist.blim: interval(0, 0.4)
  callbacks:
    clear_cache: 
      _target_: pretrained-models_aug.mycallback

data:
  trainX: data/raw/P8_Cityscapes_leftImg8bit_trainvaltest/leftImg8bit/train
  trainY: data/raw/P8_Cityscapes_gtFine_trainvaltest/gtFine/train
  validX: data/raw/P8_Cityscapes_leftImg8bit_trainvaltest/leftImg8bit/val
  validY: data/raw/P8_Cityscapes_gtFine_trainvaltest/gtFine/val
  input_height: 128
  input_width: 256

generator:
  workers: 16
  batch_size: 16
  auglist:
    geo: hflip_rotateb_rdcrop
    col: bricon
    ker: gnoise_mblur
    clim: 0.2
    blim: 0.2 
  mosaic:
  oversampling:
  seed: 42
  
model:
  loss_function: DiceLoss
  optimizer: adam
  no_epochs: 15
  verbosity: 2
  name: FPN
  backbone: efficientnetb4
  model_type: fpn


mlflow:
  experiment_name: fpn_efficientnetb4_aug
