user_config:

generator:
  auglist: hflip_rotateb_gnoise
  oversampling:
  mosaic:
  
model:
  name: FPN
  backbone: efficientnetb4
  model_type: fpn


mlflow:
  experiment_name: pretrained_fpn
  run_name: fpn_effnet_smallaug
